### ISSUE TITLE
Error after upgrading to angular 9. Unable to run the application

### ISSUE THREAD

**Issue by rammohangowd** [yobryon/ngx-barcode#24]
Hi Team,

I am able to install ngx-barcode in angular 8 version but not in angular 9.1.1. Tried "enableIvy": false and also "aot": false, still no luck. any alternate solution for this please suggest?

Getting below error before disabling the ivy.

>  ERROR in node_modules/ngx-barcode/ngx-barcode.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
>     
>     This likely means that the library (ngx-barcode) which declares NgxBarcodeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

After disabling Ivy still error like below:

> ERROR TypeError: Cannot read property 'nativeElement' of undefined
> 
>     at NgxBarcodeComponent.push../node_modules/ngx-barcode/index.js.NgxBarcodeComponent.createBarcode (index.js:88)
> 
>     at NgxBarcodeComponent.push../node_modules/ngx-barcode/index.js.NgxBarcodeComponent.ngOnChanges (index.js:65)
> 
>     at checkAndUpdateDirectiveInline (core.js:22677)
> 
>     at checkAndUpdateNodeInline (core.js:31501)
> 
>     at checkAndUpdateNode (core.js:31463)
> 
>     at debugCheckAndUpdateNode (core.js:32100)
> 
>     at debugCheckDirectivesFn (core.js:32060)
> 
>     at Object.eval [as updateDirectives] (BarCodeComponent.html:109)
> 
>     at Object.debugUpdateDirectives [as updateDirectives] (core.js:32052)
> 
>     at checkAndUpdateView (core.js:31445)

**Comment by ZhipengZeng** [comment]
have the same issue

**Comment by adoyhamboure** [comment]
I have exactly the same issue on Angular 9.0.0
`core.js:5828 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at NgxBarcodeComponent.push.../../node_modules/ngx-barcode/__ivy_ngcc__/index.js.NgxBarcodeComponent.createBarcode (index.js:91)
    at NgxBarcodeComponent.push.../../node_modules/ngx-barcode/__ivy_ngcc__/index.js.NgxBarcodeComponent.ngOnChanges (index.js:68)`

It's working on another project on Angular 8.2.14

**Comment by salimchemes** [comment]
there is a PR with the fix already [here](https://github.com/yobryon/ngx-barcode/pull/20)
Since it was not merged yet, what I did in the meantime, was add the the component with the fix as part of my app until we have the new version released. 

```
  @ViewChild('bcElement') bcElement: ElementRef; // before
  @ViewChild('bcElement', {static: true}) bcElement: ElementRef; // after
```

**Comment by adoyhamboure** [comment]
@yobryon Could you merge this PR ? That would helps a lot of people !

**Comment by yobryon** [comment]
pr merged. Thank you to @fbjerggaard 

As per my note #25 - anyone interested in becoming a collaborator on this project, please msg me.

**Comment by adoyhamboure** [comment]
Thank you man ! Maybe you should publish the new release of your package on npm !
I could help on the project if you need, but I don't think there is a lot to add on the project, we just needed a fix for Angular 9 !
Thank you for your efforts @yobryon and thank you @fbjerggaard for the fix !

**Comment by yobryon** [comment]
@adoyhamboure it took a bit to clean up the build system and get this to compile, but I have gone ahead and published a new version (0.3.0) with this fix for angular 9. I did some quick tests porting the demo app over to angular 9 to be sure it would run against both versions.

Again, thanks to all those who contributed.

**Comment by pawel-k-kazmierczak** [comment]
Hi @yobryon,
I installed version 0.3.0 but unfortunately  get the same error. 


```
ng serve
Compiling ngx-barcode : main as commonjs

ERROR in node_modules/ngx-barcode/ngx-barcode.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-barcode) which declares NgxBarcodeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class NgxBarcodeModule {
```

I tested it at two applications.

**Comment by Ankit199** [comment]
Hi Team ,

I am facing  below error.
![image](https://user-images.githubusercontent.com/13369745/159792462-558a5578-a936-4584-b9af-47735b6b202a.png)


it was working fine last few months ..but getting error past 2 days

**Comment by Ankit199** [comment]
@Team Waiting for reply to fix issue.

**Comment by abdullah37406** [comment]
> Hi Team ,
> 
> I am facing below error. ![image](https://user-images.githubusercontent.com/13369745/159792462-558a5578-a936-4584-b9af-47735b6b202a.png)
> 
> it was working fine last few months ..but getting error past 2 days

is it solved
